# Generated by Django 3.0.7 on 2020-07-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='messages',
            field=models.TextField(default=1000),
            preserve_default=False,
        ),
    ]
