# Generated by Django 3.0.7 on 2020-07-21 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0002_contact_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='messages',
            new_name='message',
        ),
    ]
